CREATE TABLE public.questionnaire_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  responses JSONB,
  qualified TEXT CHECK (qualified IN ('calendar', 'discord'))
);

-- Enable Row Level Security (RLS) for the table.
-- This is a critical security step that ensures policies are enforced.
ALTER TABLE public.questionnaire_responses ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anonymous users (the public 'anon' role)
-- to insert new records into the questionnaire_responses table.
-- The `WITH CHECK (true)` condition means the insert is allowed as long
-- as it conforms to the table's column constraints.
CREATE POLICY "Allow anonymous questionnaire submissions"
ON public.questionnaire_responses FOR INSERT TO anon WITH CHECK (true);
