# .github/workflows/deploy.yml

name: Build and Deploy Website

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  # --- Install Job ---
  # This job checks out the code, sets up Node.js, and installs dependencies.
  # The installed node_modules are cached for use in the next job.
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your desired Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 'ci' is recommended for CI environments for faster, more reliable installs

      - name: Upload node_modules artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules/

  # --- Build and Deploy Job ---
  # This job depends on the 'install' job. It downloads the installed
  # dependencies, builds the project, and then deploys it.
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: install # This ensures the 'install' job completes successfully first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Must match the version in the install job

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules/

      - name: Build website
        run: npm run build
        env:
          CI: false # Add environment variables if your build process needs them

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # IMPORTANT: Change this to your project's build output directory
